// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxgsxoeftaqcpbjmsacn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4Z3N4b2VmdGFxY3Biam1zYWNuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMwNjkxMzAsImV4cCI6MjA4ODY0NTEzMH0.BhM-uy2_-cE9eNyJ03sw6J5pKaGlLtcuNf0W0FCy4kQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});